(library
 (name vct)
 (libraries minisat)
 (inline_tests)
 (preprocess
  (pps ppx_inline_test)))

; this cannot be qualified as bindings.ml requires some modules in gen/
; and gen/CplSolver.ml requires bindings.ml.

(include_subdirs unqualified)

(menhir
 (modules parser))

(ocamllex lexer)

; disable unused open and unused rec warnings in the generated code

(env
 (dev
  (flags
   (:standard -w -33-39))))
